### ISSUE TITLE
Support low priority tasks

### ISSUE THREAD

**Issue by davel** [p-alik/perl-Gearman#6] opened 2017-02-01 11:27 UTC
The protocol supports a "low" priority level, in addition to "high" and "normal", which the client currently implements. See https://github.com/gearman/gearmand/blob/33fccc5390dc67afc2a3fea36ea0bfecfe36b44b/PROTOCOL#L165

Could we add support for low priority tasks in the client?

**Comment by p-alik** [comment] 2017-02-01 11:41
thanks for pointing to the issue @davel. It should be done soon.

**Comment by p-alik** [comment] 2017-02-09 21:12
@davel, the issue is solved in 099053a. I'll close it as soon as new version is uploaded to cpan

**Comment by p-alik** [comment] 2017-02-18 20:47
@davel, the issue is done. This is a part of [2.003_001](https://metacpan.org/pod/release/PALIK/Gearman-v2.003_001/lib/Gearman/Client.pm) release.

**Closed as completed by p-alik** 2017-02-18 20:47 UTC
Labels: enhancement

**Comment by davel** [comment] 2017-02-18 23:08
Awesome, thank you!
